_wandb:
    value:
        cli_version: 0.23.1
        e:
            f1vcbboyv74fl0kowkm6ki8c4ogb35kq:
                args:
                    - --do_predict
                    - --task
                    - generation
                    - --table_name
                    - N10k_text_rank
                    - --model_name
                    - /gpfs/work5/0/prjs1828/DSI-QG/local_models/t5-headline
                    - --per_device_eval_batch_size
                    - "32"
                    - --run_name
                    - docTquery-N10k-generation
                    - --max_length
                    - "256"
                    - --valid_file
                    - /data/enron.db
                    - --output_dir
                    - temp
                    - --dataloader_num_workers
                    - "10"
                    - --report_to
                    - wandb
                    - --logging_steps
                    - "100"
                    - --num_return_sequences
                    - "1"
                codePath: run.py
                codePathLocal: run.py
                cpu_count: 72
                cpu_count_logical: 72
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "270183575552"
                        used: "5103099904"
                email: daniel@vanoosteroom.com
                executable: /gpfs/work5/0/prjs1828/DSI-QG/.venv/bin/python
                git:
                    commit: 4cb17c38394bf225a3f185174cb7f834bb170714
                    remote: git@github.com:daszo/snellius-code.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-926f4377-c686-b7da-8ef0-0bd89271f2a9
                host: gcn60.local.snellius.surf.nl
                memory:
                    total: "540631130112"
                os: Linux-5.14.0-427.92.1.el9_4.x86_64-x86_64-with-glibc2.34
                program: /gpfs/work5/0/prjs1828/DSI-QG/run.py
                python: CPython 3.9.18
                root: /gpfs/work5/0/prjs1828/DSI-QG
                slurm:
                    cluster_name: snellius
                    conf: /var/spool/slurm/slurmd/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x00003FFFF000000000
                    cpu_bind_list: "0x00003FFFF000000000"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "18"
                    eclibr: "0"
                    ecplug: "1"
                    erlast: srun
                    ersrun: "1"
                    export_env: ALL
                    gpus: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: gisr113267
                    job_cpus_per_node: "18"
                    job_end_time: "1765968980"
                    job_gid: "75473"
                    job_group: dvoosteroom
                    job_id: "17652128"
                    job_name: bash
                    job_nodelist: gcn60
                    job_num_nodes: "1"
                    job_partition: gpu_a100
                    job_qos: normal
                    job_start_time: "1765965380"
                    job_uid: "76013"
                    job_user: dvoosteroom
                    jobid: "17652128"
                    launch_node_ipaddr: 172.18.63.192
                    localid: "0"
                    mpi_type: pmi2
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gcn60
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "45441"
                    pty_win_col: "210"
                    pty_win_row: "54"
                    script_context: prolog_task
                    srun_comm_host: 172.18.63.192
                    srun_comm_port: "43643"
                    step_gpus: "2"
                    step_gres: gres/cpu:0
                    step_id: "0"
                    step_launcher_port: "43643"
                    step_nodelist: gcn60
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_resv_ports: 13250-13251
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /gpfs/work5/0/prjs1828/DSI-QG
                    submit_host: int6.local.snellius.surf.nl
                    task_pid: "3482065"
                    tasks_per_node: "1"
                    topology_addr: root.ibsw25.gcn60
                    topology_addr_pattern: switch.switch.node
                    umask: "0027"
                startedAt: "2025-12-17T10:00:33.326255Z"
                writerId: f1vcbboyv74fl0kowkm6ki8c4ogb35kq
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
            "3":
                - 13
            "4": 3.9.18
            "5": 0.23.1
            "6": 4.21.0
            "12": 0.23.1
            "13": linux-x86_64
